[package]
name = "authenticator-rs"
version = "0.0.1"
license = "GPL-3,0-or-later"
description = "authenticator-rs"
readme = "README.md"
homepage = "https://github.com/grumlimited/authenticator-rs/"
repository = "https://github.com/grumlimited/authenticator-rs/"
authors = ["Romain Gallet <rgallet@grumlimited.co.uk>"]
edition = "2018"

[dependencies]
anyhow = "1.0.36"
base32 = "0.4.0"
bytes = "0.5.6"
chrono = "0.4.19"
curl = "0.4.34"
directories = "3.0.1"
futures = {version = "0.3.8", features = ["thread-pool"]}
futures-executor = "0.3.8"
gdk = "0.13.2"
gdk-pixbuf = "0.9.0"
gettext-rs = {version = "0.5.0", features = ["gettext-system"]}
gio = "0.9.1"
log = "0.4.11"
log4rs = "0.12.0"
refinery = { version = "0.4.0", features = ["rusqlite"]}
regex = "1.4.2"
rusqlite = "0.24.2"
scraper = "0.12.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
serde_yaml = "0.8.14"
tempfile-fast = "0.3.3"
thiserror = "1.0.22"
totp-rs = "0.6.3"
uuid = { version = "0.8.1", features = ["v4"] }

[dependencies.gtk]
version = "0.9.2"
features = ["v3_24"]

[dependencies.glib]
version = "0.10.3"

[dev-dependencies]
async-std = {version ="1.8.0", features = [] }
